#!/bin/zsh
# This script solves the 'Pick your favorite'
# bash script challenge

echo -en "Which would you choose [pizza hamburger cake]:"
read choice  # Read user input

case $choice in
	pizza)
		echo "\e[1;33mYum, great choice\e[m"
		;;
	hamburger)
		echo "\e[1;34mAwesome. It comes with fries\e[m"
		;;
	cake)
		echo "What kind of cake?"
		read cake
		echo "\e[1;31mGreat,enjoy your \e[1;32m$cake \e[1;31mcake\e[m"
		;;
	*)
		echo "Sorry, $choice is not on the list.Pick pizza, hamburger or cake"
		;;
esac
