#!/bin/bash
# This script solves the list and sort directories
# bash script challenge. It takes a list of 
# directories and lists their files

function usage(){
	echo "$0 [[-a path] [-d path] ...] path"
	echo "List all file in the given directory"
	echo "	Options:"
	echo "		-a	Sort files in ascending order"
	echo "		-d	Sort files in descending order"
	echo "		-h	Print this message"
	echo "	Arguments:"
	echo "		path 	List files in directory"
	echo "$1"
	
	exit
}

function list_files(){
	list=""
	if [[ -d $1 ]]; then
		list="\e[1;30mListing files in $1\e[m"
		case $2 in
			"d")
				list="${list}\n$(ls --sort -r $1)\n"
				;;
			"a")
				list="${list}\n$(ls --sort $1)\n"
				;;
			*)

				list="${list}\n$(ls $1)\n"
				;;
		esac
		lists="${lists}\n${list}"
		return 0
	else
		usage "Invalid path"
	fi
}

lists=""

while getopts ":a:d:h" opts;do
	case $opts in
		"a")
			list_files $OPTARG a
			;;
		"d")
			list_files $OPTARG d
			;;
		"h")
			usage
			;;
		*)
			usage "Invalid option" 
			;;
	esac
done

for path in $@; do
	list_files "$path"
done

if [[ -n "$lists" ]]; then
	echo -e "$lists"
else
	usage
fi

